### ISSUE TITLE
Problems with gulp production

### ISSUE THREAD

**Issue by ldelcampof** [Media24si/vue-pagination#12]
Always when I'm trying to minify my app, Gulp throw me this error
`{ Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)
    at expect_token (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:20)
    at expect (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)
    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at expr_atom (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)
  message: '/Users/ldelcampo/Sites/crm/app.js: Unexpected character \'`\'',
  fileName: '/Users/ldelcampo/Sites/crm/app.js',
  lineNumber: 148,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)\n    at parse_error (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)\n    at Object.next_token [as input] (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)\n    at next (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)\n    at expect_token (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:20)\n    at expect (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)\n    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)\n    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)\n    at expr_atom (eval at <anonymous> (/Users/ldelcampo/Sites/crm/node_modules/laravel-elixir/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }`

but when try without minify the code, everything works properly. Searching on the code is about template literals with the backtick, but is not the only thing that gulp doesn't supports, can you help me?

**Comment by pogachar** [comment]
you probably need to transpile your code from es6 to es5 before minifying it.
try with  [gulp babel](https://github.com/babel/gulp-babel)

personally I'd recommend [laravel elixir](https://github.com/laravel/elixir), since it's very easy to implement

**Comment by ldelcampof** [comment]
I am using elixir from laravel, but when try to use **gulp production** the error come up

**Comment by ldelcampof** [comment]
@pogachar this is my gulpfile.js for this time:

```
elixir((mix) => {
    mix.sass('app.scss')
       .webpack('app.js');
});
```
and the error show up when try to use gulp --production in a laravel project
