### ISSUE TITLE
Error on gulp --production with elixir 6 

### ISSUE THREAD

**Issue by ldelcampof** [Media24si/vue-pagination#14]
I'm still having this issue, help please!! babel is include since elixir 5, so i don't know what to do in this case

```
[13:16:42] ldelcampo:molinillos git:(master*) $ gulp --production
[13:19:37] Using gulpfile ~/Sites/molinillos/gulpfile.js
[13:19:37] Starting 'all'...
[13:19:37] Starting 'sass'...
[13:19:37] Finished 'sass' after 306 ms
[13:19:37] Starting 'webpack'...
{ Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)
    at expect_token (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:20)
    at expect (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)
    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at expr_atom (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)
  message: '/Users/ldelcampo/Sites/molinillos/app.js: Unexpected character \'`\'',
  fileName: '/Users/ldelcampo/Sites/molinillos/app.js',
  lineNumber: 11365,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)\n    at parse_error (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)\n    at Object.next_token [as input] (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)\n    at next (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)\n    at expect_token (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:20)\n    at expect (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)\n    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)\n    at eval (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)\n    at expr_atom (eval at <anonymous> (/Users/ldelcampo/Sites/molinillos/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }

```

**Comment by pogachar** [comment]
Any chance you could make a demo repository with the same bug and setup?

**Comment by ldelcampof** [comment]
Ready on https://github.com/ldelcampof/hotel-demo

**Comment by pogachar** [comment]
I got it to work, I need to edit the package a bit but it's very late here so I'll do it first thing tomorrow after work.

**Comment by pogachar** [comment]
It looks like the problem is with laravel-elixir-webpack-official. if you change the version to `1.0.8` (without ^) it works ok. Latest 2 versions don't work.

**Comment by ldelcampof** [comment]
thanks! I will try right now
